import { type AccentColors, accents, defaultAccent } from "./accent";
import { type ColorScheme, dark, light } from "./color";
import { radius, space } from "./layout";
import { duration, easing } from "./motion";
import { fontFamily, minimumTextSize, textStyles } from "./typography";

const kebab = (key: string) => key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/**
 * Text styles scale together with `--type-scale` (set from the reader's text
 * size), never below the smallest style. Line heights are separate
 * `leading-*` utilities, so adopting a size never moves existing leading.
 */
function textStyleVars(): string[] {
  return Object.entries(textStyles).flatMap(([name, style]) => {
    const scaled = (px: number) =>
      `max(${Math.min(px, minimumTextSize)}px, calc(${px}px * var(--type-scale, 1)))`;
    return [
      `  --text-${kebab(name)}: ${scaled(style.size)};`,
      `  --leading-${kebab(name)}: ${scaled(style.lineHeight)};`,
    ];
  });
}

function colorVars(scheme: ColorScheme | AccentColors): string {
  return Object.entries(scheme)
    .map(([key, value]) => `  --color-${kebab(key)}: ${value};`)
    .join("\n");
}

/**
 * Renders the tokens as a Tailwind v4 compatible stylesheet. Light values
 * live in `@theme`; dark values apply with the system's dark appearance, or
 * through `data-theme`. Like SwiftUI's `colorScheme` environment,
 * `data-theme="dark"` or `"light"` works on any element, not only the root,
 * so one part of a screen can keep its own appearance (an always-dark
 * recorder, an always-white invoice). Accents other than the default apply
 * through `data-accent` on the root element.
 */
export function renderThemeCss(): string {
  const others = Object.values(accents).filter((accent) => accent.id !== defaultAccent);
  const lines = [
    "/* Generated by @ultrapeach/tokens. Do not edit by hand. */",
    "@theme static {",
    colorVars(light),
    ...Object.entries(fontFamily).map(([k, v]) => `  --font-${k}: ${v};`),
    ...textStyleVars(),
    ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${v}px;`),
    ...Object.entries(space).map(([k, v]) => `  --space-${k}: ${v}px;`),
    ...Object.entries(duration).map(([k, v]) => `  --duration-${k}: ${v}ms;`),
    ...Object.entries(easing).map(([k, v]) => `  --ease-${k}: ${v};`),
    "}",
    "",
    // Native controls, scrollbars and form fills follow the same appearance.
    ":root { color-scheme: light dark; }",
    '[data-theme="light"] { color-scheme: light; }',
    '[data-theme="dark"] { color-scheme: dark; }',
    "",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    colorVars(dark).replace(/^/gm, "  "),
    "  }",
    "}",
    "",
    '[data-theme="dark"] {',
    colorVars(dark),
    "}",
    "",
    // A light part inside a dark screen needs the light values back.
    ':root [data-theme="light"] {',
    colorVars(light),
    "}",
    "",
    ...others.flatMap((accent) => {
      const root = `:root[data-accent="${accent.id}"]`;
      return [
        `${root}, ${root} [data-theme="light"] {`,
        colorVars(accent.light),
        "}",
        "@media (prefers-color-scheme: dark) {",
        `  ${root}:not([data-theme="light"]) {`,
        colorVars(accent.dark).replace(/^/gm, "  "),
        "  }",
        "}",
        `${root}[data-theme="dark"], ${root} [data-theme="dark"] {`,
        colorVars(accent.dark),
        "}",
        "",
      ];
    }),
  ];
  return lines.join("\n");
}
