import { type ColorScheme, dark, light } from "./color.ts";
import { radius, space } from "./layout.ts";
import { duration, easing } from "./motion.ts";
import { fontFamily } from "./typography.ts";

const kebab = (key: string) => key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

function colorVars(scheme: ColorScheme): string {
  return Object.entries(scheme)
    .map(([key, value]) => `  --color-${kebab(key)}: ${value};`)
    .join("\n");
}

/**
 * Renders the tokens as a Tailwind v4 compatible stylesheet. Light values
 * live in `@theme`; dark values override them via `prefers-color-scheme`
 * or an explicit `data-theme="dark"` on the root element.
 */
export function renderThemeCss(): string {
  const lines = [
    "/* Generated by @notables/design-tokens — do not edit by hand. */",
    "@theme {",
    colorVars(light),
    ...Object.entries(fontFamily).map(([k, v]) => `  --font-${k}: ${v};`),
    ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${v}px;`),
    ...Object.entries(space).map(([k, v]) => `  --space-${k}: ${v}px;`),
    ...Object.entries(duration).map(([k, v]) => `  --duration-${k}: ${v}ms;`),
    ...Object.entries(easing).map(([k, v]) => `  --ease-${k}: ${v};`),
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    colorVars(dark).replace(/^/gm, "  "),
    "  }",
    "}",
    "",
    ':root[data-theme="dark"] {',
    colorVars(dark),
    "}",
    "",
  ];
  return lines.join("\n");
}
