/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as PPublicationIdRouteImport } from './routes/p/$publicationId'
import { Route as ReadBookIdRouteImport } from './routes/read/$bookId'
import { Route as AppBooksIndexRouteImport } from './routes/_app/books/index'
import { Route as AppBooksBookIdRouteImport } from './routes/_app/books/$bookId'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'
import { Route as MediaPublicationIdMediaIdRouteImport } from './routes/media/$publicationId/$mediaId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const PPublicationIdRoute = PPublicationIdRouteImport.update({
  id: '/p/$publicationId',
  path: '/p/$publicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksBookIdRoute = AppBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const MediaPublicationIdMediaIdRoute =
  MediaPublicationIdMediaIdRouteImport.update({
    id: '/media/$publicationId/$mediaId',
    path: '/media/$publicationId/$mediaId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/p/$publicationId': typeof PPublicationIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/media/$publicationId/$mediaId': typeof MediaPublicationIdMediaIdRoute
  '/books/': typeof AppBooksIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AppSettingsRoute
  '/p/$publicationId': typeof PPublicationIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/': typeof AppIndexRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/media/$publicationId/$mediaId': typeof MediaPublicationIdMediaIdRoute
  '/books': typeof AppBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/p/$publicationId': typeof PPublicationIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/books/$bookId': typeof AppBooksBookIdRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/media/$publicationId/$mediaId': typeof MediaPublicationIdMediaIdRoute
  '/_app/books/': typeof AppBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/p/$publicationId'
    | '/read/$bookId'
    | '/books/$bookId'
    | '/notes/$noteId'
    | '/media/$publicationId/$mediaId'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/p/$publicationId'
    | '/read/$bookId'
    | '/'
    | '/books/$bookId'
    | '/notes/$noteId'
    | '/media/$publicationId/$mediaId'
    | '/books'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/p/$publicationId'
    | '/read/$bookId'
    | '/_app/'
    | '/_app/books/$bookId'
    | '/_app/notes/$noteId'
    | '/media/$publicationId/$mediaId'
    | '/_app/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PPublicationIdRoute: typeof PPublicationIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
  MediaPublicationIdMediaIdRoute: typeof MediaPublicationIdMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$publicationId': {
      id: '/p/$publicationId'
      path: '/p/$publicationId'
      fullPath: '/p/$publicationId'
      preLoaderRoute: typeof PPublicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/books/': {
      id: '/_app/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId': {
      id: '/_app/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AppBooksBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/media/$publicationId/$mediaId': {
      id: '/media/$publicationId/$mediaId'
      path: '/media/$publicationId/$mediaId'
      fullPath: '/media/$publicationId/$mediaId'
      preLoaderRoute: typeof MediaPublicationIdMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBooksBookIdRoute: typeof AppBooksBookIdRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBooksBookIdRoute: AppBooksBookIdRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PPublicationIdRoute: PPublicationIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
  MediaPublicationIdMediaIdRoute: MediaPublicationIdMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
