/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as ModelsSplatRouteImport } from './routes/models/$'
import { Route as PPublicationIdRouteImport } from './routes/p/$publicationId'
import { Route as ReadBookIdRouteImport } from './routes/read/$bookId'
import { Route as SShareIdRouteImport } from './routes/s/$shareId'
import { Route as AppBooksIndexRouteImport } from './routes/_app/books/index'
import { Route as AppBooksBookIdRouteImport } from './routes/_app/books/$bookId'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'
import { Route as MediaPublicationIdMediaIdRouteImport } from './routes/media/$publicationId/$mediaId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const ModelsSplatRoute = ModelsSplatRouteImport.update({
  id: '/models/$',
  path: '/models/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PPublicationIdRoute = PPublicationIdRouteImport.update({
  id: '/p/$publicationId',
  path: '/p/$publicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksBookIdRoute = AppBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const MediaPublicationIdMediaIdRoute =
  MediaPublicationIdMediaIdRouteImport.update({
    id: '/media/$publicationId/$mediaId',
    path: '/media/$publicationId/$mediaId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/widget': typeof WidgetRoute
  '/calendar': typeof AppCalendarRoute
  '/connections': typeof AppConnectionsRoute
  '/settings': typeof AppSettingsRoute
  '/trash': typeof AppTrashRoute
  '/models/$': typeof ModelsSplatRoute
  '/p/$publicationId': typeof PPublicationIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/s/$shareId': typeof SShareIdRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/media/$publicationId/$mediaId': typeof MediaPublicationIdMediaIdRoute
  '/books/': typeof AppBooksIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/widget': typeof WidgetRoute
  '/calendar': typeof AppCalendarRoute
  '/connections': typeof AppConnectionsRoute
  '/settings': typeof AppSettingsRoute
  '/trash': typeof AppTrashRoute
  '/models/$': typeof ModelsSplatRoute
  '/p/$publicationId': typeof PPublicationIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/s/$shareId': typeof SShareIdRoute
  '/': typeof AppIndexRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/media/$publicationId/$mediaId': typeof MediaPublicationIdMediaIdRoute
  '/books': typeof AppBooksIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/widget': typeof WidgetRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trash': typeof AppTrashRoute
  '/models/$': typeof ModelsSplatRoute
  '/p/$publicationId': typeof PPublicationIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/s/$shareId': typeof SShareIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/books/$bookId': typeof AppBooksBookIdRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/media/$publicationId/$mediaId': typeof MediaPublicationIdMediaIdRoute
  '/_app/books/': typeof AppBooksIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify'
    | '/welcome'
    | '/widget'
    | '/calendar'
    | '/connections'
    | '/settings'
    | '/trash'
    | '/models/$'
    | '/p/$publicationId'
    | '/read/$bookId'
    | '/s/$shareId'
    | '/books/$bookId'
    | '/invoices/$invoiceId'
    | '/notes/$noteId'
    | '/media/$publicationId/$mediaId'
    | '/books/'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/verify'
    | '/welcome'
    | '/widget'
    | '/calendar'
    | '/connections'
    | '/settings'
    | '/trash'
    | '/models/$'
    | '/p/$publicationId'
    | '/read/$bookId'
    | '/s/$shareId'
    | '/'
    | '/books/$bookId'
    | '/invoices/$invoiceId'
    | '/notes/$noteId'
    | '/media/$publicationId/$mediaId'
    | '/books'
    | '/invoices'
  id:
    | '__root__'
    | '/_app'
    | '/verify'
    | '/welcome'
    | '/widget'
    | '/_app/calendar'
    | '/_app/connections'
    | '/_app/settings'
    | '/_app/trash'
    | '/models/$'
    | '/p/$publicationId'
    | '/read/$bookId'
    | '/s/$shareId'
    | '/_app/'
    | '/_app/books/$bookId'
    | '/_app/invoices/$invoiceId'
    | '/_app/notes/$noteId'
    | '/media/$publicationId/$mediaId'
    | '/_app/books/'
    | '/_app/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  WidgetRoute: typeof WidgetRoute
  ModelsSplatRoute: typeof ModelsSplatRoute
  PPublicationIdRoute: typeof PPublicationIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
  SShareIdRoute: typeof SShareIdRoute
  MediaPublicationIdMediaIdRoute: typeof MediaPublicationIdMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/models/$': {
      id: '/models/$'
      path: '/models/$'
      fullPath: '/models/$'
      preLoaderRoute: typeof ModelsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$publicationId': {
      id: '/p/$publicationId'
      path: '/p/$publicationId'
      fullPath: '/p/$publicationId'
      preLoaderRoute: typeof PPublicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/books/': {
      id: '/_app/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId': {
      id: '/_app/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AppBooksBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/media/$publicationId/$mediaId': {
      id: '/media/$publicationId/$mediaId'
      path: '/media/$publicationId/$mediaId'
      fullPath: '/media/$publicationId/$mediaId'
      preLoaderRoute: typeof MediaPublicationIdMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrashRoute: typeof AppTrashRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBooksBookIdRoute: typeof AppBooksBookIdRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrashRoute: AppTrashRoute,
  AppIndexRoute: AppIndexRoute,
  AppBooksBookIdRoute: AppBooksBookIdRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  WidgetRoute: WidgetRoute,
  ModelsSplatRoute: ModelsSplatRoute,
  PPublicationIdRoute: PPublicationIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
  SShareIdRoute: SShareIdRoute,
  MediaPublicationIdMediaIdRoute: MediaPublicationIdMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
