/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PPublicationIdRouteImport } from './routes/p/$publicationId'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PPublicationIdRoute = PPublicationIdRouteImport.update({
  id: '/p/$publicationId',
  path: '/p/$publicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/p/$publicationId': typeof PPublicationIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
}
export interface FileRoutesByTo {
  '/p/$publicationId': typeof PPublicationIdRoute
  '/': typeof AppIndexRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/p/$publicationId': typeof PPublicationIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$publicationId' | '/notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/p/$publicationId' | '/' | '/notes/$noteId'
  id:
    | '__root__'
    | '/_app'
    | '/p/$publicationId'
    | '/_app/'
    | '/_app/notes/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PPublicationIdRoute: typeof PPublicationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$publicationId': {
      id: '/p/$publicationId'
      path: '/p/$publicationId'
      fullPath: '/p/$publicationId'
      preLoaderRoute: typeof PPublicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PPublicationIdRoute: PPublicationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
